[Feature] 사진 여러장 올리는 기능 및 게시물과 사진 한꺼번에 올리는 기능 추가
Samsamhada/Giwazip-Server pull request #75
Opened 2023-02-09 20:03 UTC by taek0622

## Motivation 🥳 (코드를 추가/변경하게 된 이유)
- 한 번에 여러 사진을 업로드하기 위함
- 게시물을 생성할 때, 사진도 한꺼번에 업로드 하기 위함

## Key Changes 🔥 (주요 구현/변경 사항)
- 한 번에 여러 사진을 업로드 하는 기능 추가 (`photos.createMulti`)
- 게시물 생성시 사진도 한번에 업로드 하는 기능 추가 `(posts.createWithPhotos`)

## ToDo 📆 (남은 작업)
- [ ] 애플 로그인 (업자용)
- [ ] 게시물과 사진 한번에 업로드 하는 기능 테스트

## ScreenShot 📷 (참고 사진)
- 없음

## To Reviewers 🙏 (리뷰어에게 전달하고 싶은 말)
- 드디어 중요한 기능들은 전부 끝났습니다. 후에 더 필요한게 있다면 추가하는 쪽으로 가면 될 것 같습니다.
- 현재, 사진을 여러장 한번에 업로드 하는 기능은 테스트까지 모두 마쳤으나, 게시물과 사진을 한꺼번에 올리는 기능은 Postman 만으로는 확인이 어려워 테스트 하지 못했습니다. 해당 부분은 고객용 앱에서 해당 기능을 다룰 때 다시 테스트 하면서 수정해야할 것 같습니다. 이 부분 양해 부탁드려요.
- 로그에 대한 부분도 마무리 되었다고 생각하여 로그 이슈도 한꺼번에 닫습니다.
- multer를 통해서 여러 이미지 업로드 하는 부분, Sequelize의 bulkCreate 메서드를 통해 여러 데이터 행을 추가하는 부분 아래에 레퍼런스로 달아놓습니다.
- js의 for 문과 array가 Swift와는 조금 다른데 해당 부분에 대해서도 레퍼런스 달아놓습니다.
- js의 for문과 Swift for문의 차이를 간단히 보자면 아래와 같습니다.
```javascript
// JavaScript
for (idx = 0; idx < array.length; idx++) {
    // for문 내부
}
```
```swift
// Swift
for idx in 0..<array.count {
    // fo문 내부
}
```
- js의 array와 for의 array의 차이를 간단히 보자면, for문에서는 array의 요소 개수를 셀 때 `count`를 사용하는 반면, js에서는 `length`를 사용합니다. 또한, swift에서는 배열의 새 요소를 추가할 때 `append`를 사용하지만, js에서는 `push`를 사용한다는 차이가 있습니다.

## Reference 🔗
- multer로 여러 이미지 업로드
  - [stackoverflow - Uploading multiple files with Multer](https://stackoverflow.com/questions/39350040/uploading-multiple-files-with-multer)
  - [Read me - [node.js] multer와 S3를 이용한 이미지 업로드 (multer 설치 부터 S3이미지 업로드 까지) - 1. multer](https://juhi.tistory.com/10)
  - [shitai.koto - [Node.js] Multer-S3를 이용한 이미지 업로드](https://velog.io/@shitaikoto/Node-Multer-S3-aws-sdk)
  - [zerocho.com - multer를 사용해 이미지 업로드하기](https://www.zerocho.com/category/NodeJS/post/5950a6c4f7934c001894ea83)
- 알아두면 좋은 js 문법
  - [MDN Web Docs - 루프와 반복](https://developer.mozilla.org/ko/docs/Web/JavaScript/Guide/Loops_and_iteration)
  - [MDN Web Docs - Array](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Array)
- Sequelize 한번에 여러 데이터 행 추가하기
  - [victolee - [Node.js] sequelize(3) - CRUD + RESTful 게시판 만들기](https://victorydntmd.tistory.com/29)

## Close Issues 🔒 (닫을 Issue)
- Close #40.
- Close #59.

2023-02-10 12:35 UTC, JUNY0110 requested changes

2023-02-10 12:35 UTC, JUNY0110 commented on controllers/photo.controller.js
> +            photos.push({ postID: postID, url: req.files[idx].location });
Q.
js에서 const가 변수인가요?
photos에 append하도록 되어있기에 질문합니다!

2023-02-10 12:56 UTC, taek0622 commented on controllers/photo.controller.js
> +            photos.push({ postID: postID, url: req.files[idx].location });
> Q. js에서 const가 변수인가요? photos에 append하도록 되어있기에 질문합니다!

진짜 너무 중요하고 좋은 질문입니다~ :)

js에서는 변수 상수 구분을 `const`, `let`, `var` 세 가지로 구분할 수 있는데, `const`는 상수, `let`은 지역 변수, `var`는 전역 변수이고, `var`는 비사용을 권장하고 있긴합니다.

`photos`는 상수이지만, `push`가 됩니다. 그 이유는 js에서의 array나 객체의 특이성 때문인데요. js에서 const는 블록 범위(지역) 상수를 선언하며, 상수의 값은 재할당 및 재선언이 불가능합니다.
그런데, js의 array에 push를 하거나 객체의 attribute를 바꾸는 것은 재할당이나 재선언이 아닙니다.

그 이유는 배열이나 객체를 선언한 것은 배열이나 객체의 포인터를 지정하는 것이고, push나 attribute를 바꾸는 것은 그 포인터에 접근해 포인터 안의 내용만 바꾸는 것이기 때문입니다.
그러나, js의 const는 포인터 자체를 바꾸는 행위만 금지하고 있기 때문에 js에서는 배열이나 객체를 상수, 즉 const로 선언하더라도 배열이나 객체 자체가 바뀌지 않는 이상 push 등으로 값을 바꾸는 것이 가능합니다.

2023-02-12 17:40 UTC, JUNY0110 approved these changes
고생하셨습니다. 드디어.. 끝이 났군요

2023-02-12 18:28 UTC, merged

2023-02-12 18:29 UTC, taek0622 commented
> 고생하셨습니다. 드디어.. 끝이 났군요

드디어 끝났네요.. ㅠㅠ